In [1]:
#fancy indexing

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
x = arr[[1,2,3]]
print(x)

[2 3 4]


In [5]:
#sorting
#ascending
arr = np.array([1,4,7,3,5,8,3,4])
x = arr[np.argsort(arr)]
print(x)

[1 3 3 4 4 5 7 8]


In [6]:
#descending
arr = np.array([1,4,7,3,5,8,3,4])
x = arr[np.argsort(-arr)]
print(x)

[8 7 5 4 4 3 3 1]


In [7]:
#value assign
arr = np.array([1,2,3,4,5,6,7,8])
x = [2,3,4]
y = [10,20,30]
arr[x] = y
print(arr)

[ 1  2 10 20 30  6  7  8]


In [9]:
#1
arr = np.array([10,20,30,40,50])
x = arr[[1,3,4]]
x

array([20, 40, 50])

In [10]:
#2
arr = np.array([5,10,15,20,25])
x = arr[np.argsort(-arr)]
print(x)

[25 20 15 10  5]


In [12]:
#3
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
x = arr[[2]]
x

array([[7, 8, 9]])

In [13]:
#4
arr = np.array([[10,11],
                [12,13],
                [14,15],
                [16,17]])
x = arr[[1,2]]
x

array([[12, 13],
       [14, 15]])

In [17]:
#5
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
x = arr[:,[0,2]]
x

array([[1, 3],
       [4, 6],
       [7, 9]])

In [20]:
#6
arr = np.array([10,15,20,25,30,35])
x = (arr>20)
x = arr[x]
print(x)

[25 30 35]


In [23]:
#7
arr = np.array([1,2,6,8,3,5,7,9])
x = arr>5
x = arr[x]
print(x)

[6 8 7 9]


In [24]:
#8
arr = np.array([10,20,30,40,50])
x = [0,2,4]
y = [99]
arr[x] = y
arr

array([99, 20, 99, 40, 99])

In [33]:
#9
arr = np.array([[10,11,12],
                [13,14,15],
                [16,17,18]])
x = arr[[0,1,2],[0,1,2]]
print(x)

[10 14 18]


In [34]:
#10
arr = np.array([5,10,15,20,25,30,35,40])
x = arr[[2,4,6]]
x

array([15, 25, 35])

In [49]:
#11
arr = np.array([['A','B','C'],
                ['D','E','F'],
                ['G','H','I']])
index_list = arr[[0,2,5]]
print(index_list)

IndexError: index 5 is out of bounds for axis 0 with size 3

In [56]:
#12
arr = np.array([3,6,9,12,15])
arr[arr>9] = 0
print (arr)

[3 6 9 0 0]


In [62]:
#13
arr = np.array([[[1,2],
                [3,4],
                [5,6],
                [7,8],
                [9,10],
                [11,12]]])
x = arr[[0]]
x

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [63]:
#14
arr = np.array([[10,20],
                [30,40],
                [50,60]])
row_idx = [0,1,2]
col_idx = [1,0,1]
x = arr[[row_idx],[col_idx]]
x

array([[20, 30, 60]])

In [64]:
#15
arr = np.array([1,2,3,4,5,6,7,8])
x = arr[arr%2==0]
x

array([2, 4, 6, 8])

In [73]:
#16
dict ={'a':10,'b':20, 'c':30}
arr = np.array([dict])
x = arr[[0,2]]
x

IndexError: index 2 is out of bounds for axis 0 with size 1