In [7]:
#1
import numpy as np
arr = np.arange(1,26).reshape(5,5)
print(arr)
x = arr[::2,::2]
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  3  5]
 [11 13 15]
 [21 23 25]]


In [25]:
#2
arr = np.ones((4,4),dtype=int)
arr[1:3,1:3] = 0
print(arr)

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


In [30]:
#3
arr = np.arange(1,10).reshape(3,3)
print(arr)
x = arr[: :,::-1]
x

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [31]:
#4
arr = np.arange(1,10).reshape(3,3)
print(arr)
x = arr[: :-1,: :]
x

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [44]:
#5
arr = np.arange(1,26).reshape(5,5)
print(arr)
x = arr[1::2]
print(x)
y = arr[:,: :2]
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 6  7  8  9 10]
 [16 17 18 19 20]]
[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]
 [21 23 25]]


In [48]:
#6
arr = np.arange(1,10).reshape(3,3)
print(arr)
x = arr[: , : :-1]
y = x.diagonal()
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 5 7]


In [51]:
#7
arr = np.arange(1,17).reshape(4,4)
print(arr)
x = arr[1:3,1:3]
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 6  7]
 [10 11]]


In [59]:
#8
arr = np.ones((4,4),dtype=int)
print(arr)
arr[: ,2:3] = 0
print(arr)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1 1 0 1]
 [1 1 0 1]
 [1 1 0 1]
 [1 1 0 1]]


In [61]:
#9
arr = np.arange(1,26).reshape(5,5)
print(arr)
x = arr[::,::]
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
