In [1]:
#1
import numpy as np 
arr = np.arange(1,13).reshape(3,4)
print(arr)
a = arr[1:2]
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[5 6 7 8]]


In [2]:
#2
import numpy as np 
arr = np.arange(1,13).reshape(3,4)
a = arr[1,2]
a

np.int64(7)

In [3]:
#3
import numpy as np 
arr = np.arange(1,13).reshape(3,4)
a = arr[:,2:]
a

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [4]:
#4
import numpy as np 
arr = np.arange(1,13).reshape(3,4)
a = arr[1:,:2]
a

array([[ 5,  6],
       [ 9, 10]])

In [5]:
arr = [1,2,3,4,5,6,7,8,9,10]
a = arr[-6: :-1]
a

[5, 4, 3, 2, 1]

In [6]:
arr = [1,2,3,4,5,6,7,8,9,10]
a = arr[4::-1]
print(a)

[5, 4, 3, 2, 1]
