In [3]:
#1D Array
import numpy as np
a = np.array([1,2,3,4,5,6,7,8])

In [18]:
#2D Array
import numpy as np
a = np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]])
print(a)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [26]:
#3D Array
import numpy as np
a = np.array([[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[5,4,3,2,1]]])
print(a)
print(a.ndim)
print(a.size)
print(a.dtype)
print(a.shape)
print(a.itemsize)

[[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]
  [5 4 3 2 1]]]
3
20
int64
(1, 4, 5)
8


In [28]:
#Attributes
print(a)
print(a.ndim)
print(a.size)
print(a.dtype)
print(a.shape)
print(a.itemsize)

[[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]
  [5 4 3 2 1]]]
3
20
int64
(1, 4, 5)
8
