In [30]:
#reshaping of array

In [2]:
#1d to 2d reshaping
import numpy as np
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
y = x.reshape(4,4)
print(y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [32]:
#1d to 3d reshaping
import numpy as np
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
y = x.reshape(3,2,2)
y

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [33]:
#2d to 3d reshaping
x = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
y = x.reshape(2,2,3)
print(y)
print(y.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [34]:
#flattening of array

In [35]:
#2d to 1d flattening
x = np.array([[1,2,3,4,5],[6,7,8,9,10]])
y = x.reshape(-1)
print(y)

[ 1  2  3  4  5  6  7  8  9 10]


In [36]:
#3d to 1d flattening
x = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
y = x.reshape(-1)
print(y)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [37]:
#unknown dimensions
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
y = x.reshape(3,2,-1)
print(y)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [38]:
#linspacing
x = np.linspace(0,100,50,dtype=int)
x

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97, 100])

In [39]:
#random numbers
a = np.random.random(9)
a

array([0.83788995, 0.49026872, 0.97724655, 0.90172899, 0.41272727,
       0.21029789, 0.4417608 , 0.30760921, 0.61826203])

In [1]:
a = np.random.randint(3,4,size=(3,4,5))
a

NameError: name 'np' is not defined

In [41]:
#1
arr = np.array([1,2,3,4,5,6])
new = arr.reshape(2,3)
new

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
#2
arr = np.array([1,2,3,4,5,6,7,8,9])
new = arr.reshape(2,4)

ValueError: cannot reshape array of size 9 into shape (2,4)

In [36]:
#3
arr = np.arange(12)
new = arr.reshape(2,2,3)
new

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [38]:
#4
arr = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
arr.flatten()

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [58]:
#5
arr = np.arange(24).reshape(2,3,4)
new = arr.reshape(6,-1)
print(new)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [63]:
#6
x = np.linspace(0,100,10,dtype=int)
print(x)

[  0  11  22  33  44  55  66  77  88 100]


In [67]:
#7
x = np.linspace(0,1,5,dtype=int)
print(x)

[0 0 0 0 1]


In [70]:
#8
x = np.linspace(5,20,7,endpoint = False,dtype=int)
x

array([ 5,  7,  9, 11, 13, 15, 17])

In [71]:
#9
x = np.linspace(0,5,0)
x

array([], dtype=float64)

In [73]:
#10
arr = np.array([[1,2,3],[4,5,6]])
x = arr.reshape(-1)
print(x)

[1 2 3 4 5 6]


In [74]:
#11
x = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
y = x.reshape(-1)
print(y)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [78]:
#12
x = np.array([[1,2,3,4,5,6],[5,6,7,8,9,10]])
print(x.reshape(2,3,2))
print(x.flatten())

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 5  6]
  [ 7  8]
  [ 9 10]]]
[ 1  2  3  4  5  6  5  6  7  8  9 10]


In [85]:
#13
arr = np.arange(8)
arr.reshape(-1,4)

[0 1 2 3 4 5 6 7]


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
#1
# Unknown Dimensions

In [88]:
#2
x = np.array([[1,2,3],[1,2,3]])
x.flatten()

array([1, 2, 3, 1, 2, 3])

In [89]:
#3
x = np.arange(10)
x.reshape(3,4)
x

ValueError: cannot reshape array of size 10 into shape (3,4)

In [90]:
#4
x = np.arange(12)
x.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
#5
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
#6
x = np.zeros((3,3))
print(x)
y = np.ones((3,3))
print(y)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [107]:
#7
x = np.identity(5,dtype=int)
print(x)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [112]:
#8
x = np.linspace(0,10,2,dtype=int)
print(x)

[ 0 10]


In [29]:
#9
x = np.arange(12)
x.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])