In [1]:
#boolean indexing

In [1]:
#1
import numpy as np
arr = np.arange(1,50)
boolean_mask = (arr>25)
new = arr[boolean_mask]
print(new)

[26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [3]:
#2
arr = np.arange(21)
boolean_mask = (arr%2!=0)
new = arr[boolean_mask]
print(new)

[ 1  3  5  7  9 11 13 15 17 19]


In [4]:
#3
arr = np.arange(30)
boolean_mask = (arr%2==0)
new = arr[boolean_mask]
print(new)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [5]:
#4
arr = np.arange(100)
boolean_mask = (arr>50) & (arr<80)
new = arr[boolean_mask]
print(new)

[51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79]


In [6]:
#5
arr = np.array([1,2,3,4,5,-1,-2,-3,-4])
boolean_mask = (arr<0)
new = arr[boolean_mask]
print(new)

[-1 -2 -3 -4]


In [7]:
#6
arr = np.arange(10,100)
boolean_mask = (arr%5==0)
new = arr[boolean_mask]
print(new)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [20]:
#7
arr = np.arange(20)
arr[arr>15] = -1
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 -1 -1 -1 -1]


In [17]:
#8
arr = np.random.randint(1,100,size = 10)
meannn = np.mean(arr)
boolean_mask = arr[arr > meannn]
print(boolean_mask)

[81 62 91 65 77]


In [28]:
#9
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
boolean_mask = (arr > 4)
result = arr[boolean_mask]
print(result)

[5 6 7 8 9]


In [43]:
#10
arr = np.array([[1,2,3,4],
                 [4,5,6,7],
                 [7,8,9,10],
                 [11,12,13,14]])
column = arr[:,2]
boolean_mask = (column>5)
result = column[boolean_mask]
print(result)

[ 6  9 13]


In [50]:
#11
arr = np.random.randint(10,size = 15)
print(arr)
boolean_mask = (arr == 0 )
print(boolean_mask)

[8 3 2 2 3 2 0 4 3 0 3 9 2 7 7]
[False False False False False False  True False False  True False False
 False False False]


In [55]:
#12
arr = np.array([1,2,3,4,5,1,2,3,5,6,7,8,9])
boolean_mask = np.unique(arr)
print(boolean_mask)

[1 2 3 4 5 6 7 8 9]


In [64]:
#13
arr = np.random.randint(1,20,size = 20)
standard = np.std(arr)
print(standard)
mean = np.mean(arr)
print(mean)
boolean_mask = (mean < standard)
result = arr[boolean_mask]
print(result)

6.542935121182236
9.7
[]


In [56]:
#14
arr = np.arange(100)
boolean_mask = (arr>30) & (arr<60)
result = arr[boolean_mask]
print(result)

[31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54
 55 56 57 58 59]


In [57]:
#15
arr = np.array([1,2,3,4,5,0,0,0,1,0,2,30,0,4])
boolean_mask = (arr!=0)
result = arr[boolean_mask]
print(result)

[ 1  2  3  4  5  1  2 30  4]
