In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
np.random.shuffle(arr)
print(arr)

[2 3 6 5 1 4]


In [5]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
arr1.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
np.ravel(arr1)  #it also flattens the array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
arr2 = np.array([1,2,3,3,2,5,6,7,7])
arr2

array([1, 2, 3, 3, 2, 5, 6, 7, 7])

In [10]:
np.unique(arr2)

array([1, 2, 3, 5, 6, 7])

In [12]:
arr2 = np.array([1,2,3,3,2,5])
np.resize(arr2,(2,3))

array([[1, 2, 3],
       [3, 2, 5]])

In [13]:
arr2 = np.array([1,2,3,3,2,5])
np.insert(arr2, 3, 4)

array([1, 2, 3, 4, 3, 2, 5])

In [17]:
arr3= ([1,2,3,4,5,6])
np.delete(arr3, 3)

array([1, 2, 3, 5, 6])

In [18]:
arrr = np.array([1,2,3,4,5,6,7,8,9])
np.array_split(arrr, 4)

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]