In [1]:
import numpy as np
#0 = column & 1 = rows

In [3]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,3,4])

In [6]:
arr1 = np.array([[1,2,3,4],[2,3,54,5]])
np.cumsum(arr1)

array([ 1,  3,  6, 10, 12, 15, 69, 74])

In [7]:
arr1.shape

(2, 4)

In [9]:
arr1.size

8

In [10]:
#1d to 2d array
arr1 = np.array([1,2,3,4])
arr1.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [11]:
#2d to 1d array
arr1.reshape(-1)

array([1, 2, 3, 4])