In [1]:
import numpy as np

In [3]:
arr = np.empty([])
arr

array(0.0078125)

In [5]:
arr = np.ones([4,6])
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [6]:
arr = np.zeros([4,6])
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [8]:
arr = np.arange(1,5)
arr

array([1, 2, 3, 4])

In [12]:
arr = np.random.rand(4)
arr

array([0.39028884, 0.60544692, 0.79989217, 0.73709573])

In [16]:
arr = np.random.ranf(5)
arr

array([0.50794313, 0.63978441, 0.25694659, 0.06154239, 0.0469578 ])

In [17]:
arr = np.random.randint(1,10,6)
arr

array([5, 1, 3, 3, 6, 9], dtype=int32)